dist: xenial
language: python

python:
  - 3.7

services:
  - mysql

env:
  global:
    - DJANGO_SETTINGS_MODULE=museum_webapp.settings
    - PYTHONPATH="/home/travis/build/JonoCX/museum_recommender"
    - PIP_USE_MIRRORS=true
  matrix:
    - DJANGO=3.1.1 DB=mysql

install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt

before_script:
  - mysql -e "CREATE DATABASE travis_ci_db;"
  - python manage.py migrate --settings=museum_webapp.settings

script:
  - python manage.py test --settings=museum_webapp.settings
