# Generated by Django 3.1.1 on 2020-09-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='page',
            field=models.CharField(default='default', max_length=256),
            preserve_default=False,
        ),
    ]
