# Generated by Django 3.1.1 on 2020-09-07 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('consent', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
                ('contact_outcome', models.BooleanField()),
                ('user_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDemographic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='museum_site.user')),
                ('age', models.CharField(choices=[('18-20', '18-20'), ('21-29', '21-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60+', '60+')], max_length=5)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('nonbinary', 'Non-binary'), ('other', 'Other'), ('none', 'Prefer not to say')], max_length=9)),
                ('education', models.CharField(choices=[('none-high-school', 'Less than high school'), ('high-school', 'High School'), ('college', 'College (no degree)'), ('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'Doctorate')], max_length=16)),
                ('work', models.CharField(choices=[('employed', 'Employed (full/part time or self)'), ('student', 'Student'), ('retired', 'Retired'), ('unemployed', 'Unemployed')], max_length=10)),
                ('submission_timestamp', models.DateTimeField()),
            ],
        ),
    ]
