# Generated by Django 3.1.1 on 2021-02-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0002_auto_20200908_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('art_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024, null=True)),
                ('artist', models.CharField(max_length=1024, null=True)),
                ('img_url', models.URLField(max_length=512)),
                ('img_thumbnail_url', models.URLField(max_length=512)),
                ('type_main', models.CharField(max_length=64, null=True)),
                ('type_sub', models.CharField(max_length=64, null=True)),
                ('date_range', models.CharField(max_length=128, null=True)),
                ('date', models.CharField(max_length=128, null=True)),
                ('topic', models.JSONField(null=True)),
                ('notes', models.JSONField(null=True)),
                ('culture', models.JSONField(null=True)),
                ('role', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
