# Generated by Django 3.1.1 on 2021-02-22 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0003_artwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkVisited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
    ]
