# Generated by Django 3.2.9 on 2021-11-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0006_auto_20210326_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='date',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='date_range',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='img_thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='role',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='type_main',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='type_sub',
        ),
        migrations.AddField(
            model_name='artwork',
            name='birth_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='classification',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='collection',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='death_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='earliest_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_credit',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='img_file',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='latest_date',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='linked_art_terms',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='linked_terms',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='linked_topics',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='artist',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
