# Generated by Django 3.2.9 on 2021-11-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0007_auto_20211110_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='img_location',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
