# Generated by Django 3.2.9 on 2021-11-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0008_artwork_img_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='birth_date',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='death_date',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
