# Generated by Django 3.1.1 on 2022-02-23 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0009_auto_20211124_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainKnowledge',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='museum_site.user')),
                ('art_knowledge', models.CharField(choices=[('novice', 'Novice'), ('some', 'I have got some knowledge'), ('knowledgeable', 'knowledgeable'), ('expert', 'Expert')], max_length=20)),
                ('museum_visits', models.CharField(choices=[('most days', 'Most Days'), ('once a week', 'At least once a week'), ('once a month', 'At least once a month'), ('every two to three months', 'At least once every two to three months'), ('once a year', 'At least once a year'), ('first time', 'This is my first time')], max_length=30)),
                ('view_collections', models.CharField(choices=[('most days', 'Most Days'), ('once a week', 'At least once a week'), ('once a month', 'At least once a month'), ('every two to three months', 'At least once every two to three months'), ('once a year', 'At least once a year'), ('first time', 'This is my first time')], max_length=30)),
                ('physical_visits', models.CharField(choices=[('once every 6 months', 'At least once every 6 months'), ('once a year', 'At least once a year'), ('two or three years', 'Every two or three years'), ('four or five years', 'Every four or five years'), ('six years or longer', 'I have not been to a museum/art gallery in 6 years or longer'), ('never', 'I have never visited a museum/art gallery in person')], max_length=30)),
                ('submission_timestamp', models.DateTimeField()),
            ],
        ),
    ]
