# Generated by Django 3.1.1 on 2022-03-02 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0011_auto_20220302_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCondition',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='museum_site.user')),
                ('condition', models.CharField(max_length=20)),
            ],
        ),
    ]
