# Generated by Django 3.1.1 on 2022-03-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0013_usercondition_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection_context', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('selected_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
    ]
