# Generated by Django 3.1.1 on 2022-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0014_artworkselected'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercondition',
            name='current_context',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
