# Generated by Django 3.1.1 on 2022-03-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0015_usercondition_current_context'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='execution_date',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
