# Generated by Django 3.1.1 on 2022-03-16 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0016_artwork_execution_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStudyGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_timestamp', models.DateTimeField()),
                ('intention', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('trust_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('trust_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('trust_three', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('trust_four', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('trust_five', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('relevant_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('relevant_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('relevant_three', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('relevant_four', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='PostStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_timestamp', models.DateTimeField()),
                ('part', models.CharField(max_length=10)),
                ('perceived_quality_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_quality_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_quality_three', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_quality_four', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_quality_five', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_quality_six', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_three', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_four', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_five', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_six', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_seven', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_eight', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_nine', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('perceived_effectiveness_ten', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_three', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_four', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_five', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_six', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_seven', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_eight', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('choice_satisfaction_nine', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('test_awareness_one', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('test_awareness_two', models.CharField(choices=[('completely disagree', 'Completely Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('completely agree', 'Completely Agree')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='DistractionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distraction', models.CharField(choices=[('duck', 'Duck'), ('mouse', 'Mouse'), ('elephant', 'Elephant'), ('bumblebee', 'Bumblebee')], max_length=30)),
                ('submission_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
    ]
