# Generated by Django 3.1.1 on 2022-03-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0017_distractiontask_poststudy_poststudygeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_eight',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_five',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_four',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_nine',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_seven',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_six',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_three',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='choice_satisfaction_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_eight',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_five',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_four',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_nine',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_seven',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_six',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_ten',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_three',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_effectiveness_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_five',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_four',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_six',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_three',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='perceived_quality_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='test_awareness_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudy',
            name='test_awareness_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='intention',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='relevant_four',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='relevant_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='relevant_three',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='relevant_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='trust_five',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='trust_four',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='trust_one',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='trust_three',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.AlterField(
            model_name='poststudygeneral',
            name='trust_two',
            field=models.CharField(choices=[('strongly disagree', 'Strongly Disagree'), ('disagree', 'Disagree'), ('neutral', 'Neither disagree or agree'), ('agree', 'Agree'), ('strongly agree', 'Strongly Agree')], max_length=30),
        ),
        migrations.CreateModel(
            name='RecommendedArtwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_context', models.CharField(max_length=30)),
                ('recommended_artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.user')),
            ],
        ),
    ]
