# Generated by Django 3.1.1 on 2022-06-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0019_auto_20220613_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercondition',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
