# Generated by Django 3.1.1 on 2022-07-18 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0020_auto_20220613_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercondition',
            name='current_step',
            field=models.IntegerField(default=1),
        ),
    ]
