# Generated by Django 3.1.1 on 2022-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0021_usercondition_current_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkselected',
            name='step_selected',
            field=models.IntegerField(default=-1),
        ),
    ]
