# Generated by Django 3.1.1 on 2022-07-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0022_artworkselected_step_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedartwork',
            name='recommended_step',
            field=models.IntegerField(default=1),
        ),
    ]
