# Generated by Django 3.1.1 on 2022-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum_site', '0023_recommendedartwork_recommended_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prolific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userdemographic',
            name='disability',
            field=models.CharField(choices=[('disabled', 'Identify as disabled'), ('not disabled', 'Do not identify as disabled'), ('no answer', 'Prefer not to answer')], max_length=20),
        ),
    ]
