# Generated by Django 3.1.1 on 2022-02-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('museum_site', '0009_auto_20211124_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRepresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Similarities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=4, max_digits=5)),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='museum_site.artwork')),
                ('representation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.datarepresentation')),
                ('similar_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similiar_art', to='museum_site.artwork')),
            ],
        ),
    ]
